name: CI - Build e Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar e rodar testes
        run: mvn clean verify

      - name: Build da imagem Docker
        run: docker build -t radio .

      - name: Testar execução local do container
        run: |
          docker run -d -p 8080:8080 --name radio radio
          sleep 10
          docker ps
          docker logs radio

      - name: Parar container
        run: docker stop radio
