name: CI/CD Multi-Ambiente

on:
  push:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4


      - name: Debug Secrets (não imprime o valor, só verifica se existe)
        run: |
          echo "PROD hook vazio?  '${{ secrets.RENDER_PROD_DEPLOY_HOOK }}'"
          echo "DEV hook vazio?   '${{ secrets.RENDER_DEV_DEPLOY_HOOK }}'"

      - name: Notify Render
        run: |
          echo [[ "${{ github.ref }}" == "refs/heads/master" ]]
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            curl GET "${{ secrets.RENDER_PROD_DEPLOY_HOOK }}"
          else
            curl GET "${{ secrets.RENDER_DEV_DEPLOY_HOOK }}"
          fi
